# -*- coding: utf-8 -*-
"""untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/bukharobanjai/610511117f5d085920595a7aec9134d4/untitled0.ipynb
"""

# Kalkulator Sederhana di Google Colab

def tambah(a, b):
    return a + b

def kurang(a, b):
    return a - b

def kali(a, b):
    return a * b

def bagi(a, b):
    if b != 0:
        return a / b
    else:
        return "Error: Pembagian dengan nol!"

print("Kalkulator Sederhana")
print("Pilihan operasi:")
print("1. Tambah")
print("2. Kurang")
print("3. Kali")
print("4. Bagi")

pilihan = input("Masukkan pilihan (1/2/3/4): ")

try:
    angka1 = float(input("Masukkan angka pertama: "))
    angka2 = float(input("Masukkan angka kedua: "))

    if pilihan == '1':
        hasil = tambah(angka1, angka2)
        operasi = '+'
    elif pilihan == '2':
        hasil = kurang(angka1, angka2)
        operasi = '-'
    elif pilihan == '3':
        hasil = kali(angka1, angka2)
        operasi = '*'
    elif pilihan == '4':
        hasil = bagi(angka1, angka2)
        operasi = '/'
    else:
        hasil = "Pilihan tidak valid."
        operasi = '?'

    print(f"Hasil: {angka1} {operasi} {angka2} = {hasil}")

except ValueError:
    print("Input tidak valid. Harap masukkan angka.")